---
apiVersion: v1
kind: Service
metadata:
  name: thread-exporter-service
  labels:
    app: thread-exporter
spec:
  ports:
  - name: thread-metrics
    port: 9199
    targetPort: 9199
    protocol: TCP
  selector:
    app: thread-exporter

